### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by k0lter** [dalibo/pg_activity#185]
Working on pg_activity 2.0.3 Debian package (before the bullseye hard freeze which should happen in a few days), I was not able to launch pg_activity, it crashes with following error:

```
Traceback (most recent call last):
  File "/usr/bin/pg_activity", line 281, in <module>
    min_duration=options.minduration,
  File "/usr/lib/python3/dist-packages/pgactivity/data.py", line 904, in pg_connect
    min_duration=min_duration,
  File "/usr/lib/python3/dist-packages/pgactivity/data.py", line 190, in pg_connect
    dsn_parameters=pg_conn.info.dsn_parameters,
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'info'
```
The following patch seems to fix the error and I could ship it but I wonder if it could leads to some side effects?

```
diff --git a/data.py b/data.py
index 87ee933..b28861a 100644
--- a/data.py
+++ b/data.py
@@ -187,7 +187,7 @@ class Data:
             pg_version,
             pg_num_version,
             min_duration=min_duration,
-            dsn_parameters=pg_conn.info.dsn_parameters,
+            dsn_parameters=pg_conn.get_dsn_parameters,
         )

     def try_reconnect(self) -> Optional["Data"]:
```
I also noticed that there was a lot of commits since tag 2.0.3 and I also wonder if the next release is already planned and when?

Thanks for your feedback

**Comment by dlax** [comment]
> ```
> Traceback (most recent call last):
>    File "/usr/bin/pg_activity", line 281, in <module>
>      min_duration=options.minduration,
>    File "/usr/lib/python3/dist-packages/pgactivity/data.py", line 904, in pg_connect
>      min_duration=min_duration,
>    File "/usr/lib/python3/dist-packages/pgactivity/data.py", line 190, in pg_connect
>      dsn_parameters=pg_conn.info.dsn_parameters,
> AttributeError: 'psycopg2.extensions.connection' object has no attribute 'info'
> ```
That's surprising. What version of psycopg2 are you using? connection's info attribute got added in version 2.8 (https://www.psycopg.org/docs/connection.html#connection.info) so this should work on bullseye.

> The following patch seems to fix the error and I could ship it but I wonder if it could leads to some side effects?
> 
> ```
> -            dsn_parameters=pg_conn.info.dsn_parameters,
> +            dsn_parameters=pg_conn.get_dsn_parameters,
Should be get_dsn_parameters().
To check if this work, you need to make the postgres server unavailable for a moment and see pg_activity trying to reconnect.


> I also noticed that there was a lot of commits since tag 2.0.3 and I also wonder if the next release is already planned and when?

It's not planned but we can certainly make a release shortly if it helps getting the package into bullseye before the freeze.

**Comment by dlax** [comment]
I noticed you uploaded version 2.0.3 to unstable, so I guess the issue you mentioned is resolved (hence, closing).

Also note that I just published a 2.1.0 version; it'd be very nice to have this one in next Debian. Thanks.

**Comment by k0lter** [comment]
For the record, I've tested on Debian Buster with psycopg2 2.7.x (as there was no versioned dependency on psycopg2) and to test if a backport could works as is.

Looking at the documentation, it seems that `connection.get_dsn_parameters()` and `connection.info.dsn_parameters` 
are the same (see: https://www.psycopg.org/docs/connection.html#connection.get_dsn_parameters)

Thanks for the 2.1.0 version, I will probaly upload it in a few hours.

**Comment by dlax** [comment]
pg_activity does not work with psycopg2 2.7.x; besides the 
connection.info missing, we use psycopg2.errors module that's only 
available from version 2.8.

As for a backport, I wonder if this could be done as part of PGDG 
repository (https://wiki.postgresql.org/wiki/Apt) as many postgresql 
users rely on this repository already (and it ships psycopg2 2.8.x). 
What do you think?

(Thanks for the update on version 2.1.0!)
